_BASE_: [
  '../datasets/food_container.yml',
  '../runtime.yml',
  '_base_/optimizer_300e_tiny.yml',
  '_base_/yolov7_elannet.yml',
  '_base_/yolov7_tiny_reader.yml',
]
use_gpu: false
log_iter: 5
snapshot_epoch: 5
weights: output/yolov7_tiny_300e_coco/model_final

arch: tiny
act: LeakyReLU


TrainReader:
  batch_size: 4


YOLOv7Loss:
  cls_weght: 0.5
  obj_weight: 1.0
  box_weight: 0.05
