_BASE_: [
  '../datasets/5_classes_food_container.yml',
  '../runtime.yml',
  '_base_/optimizer_300e_tiny.yml',
  '_base_/yolov7_elannet.yml',
  '_base_/yolov7_tiny_reader.yml',
]
use_gpu: true
log_iter: 5
snapshot_epoch: 5
weights: output/5_classes_food_container/model_final
pretrain_weights: https://paddledet.bj.bcebos.com/models/yolov7_l_300e_coco.pdparams

arch: tiny
act: LeakyReLU


TrainReader:
  batch_size: 16


YOLOv7Loss:
  cls_weght: 0.5
  obj_weight: 1.0
  box_weight: 0.05
